### PR TITLE
Rename the Data classes to clarify their roles in interpreting the raw

### PR DESCRIPTION
**Pull request by eflumerf**
data stream. Upgrade TrkDtcFragment to a full artdaq Fragment overlay class.

Note that these changes will break Offline and the Tracker VST until they are adjusted to use the new class names and the TrkDtcFragment overlay.

### CODE REVIEW

**Comment by eflumerf** [comment]
VST generator changes: https://github.com/Mu2e/otsdaq_mu2e_tracker/pull/5

**Comment by kutschke** [comment]
> Note that these changes will break Offline and the Tracker VST until they are adjusted to use the new class names and the TrkDtcFragment overlay.

@eflumerf How soon do you need a release of Offline that builds agains this new artdaq_core_mu2e?  Can it wait until after the collab meeting?

**Comment by eflumerf** [comment]
Yes, I'm intending for this PR to be rolled out in a fairly careful way. I'll make a PR to the Offline sometime this week to react to the changes, but then I don't think we'll deploy anything to the DAQ setups until after the CM.

**Review by gianipez — APPROVED** [review]
Everything looks good to me. Should we merge this?

**Comment by eflumerf** [comment]
Let's wait until after the Collaboration Meeting so that we can organize the change as smoothly as possible

**Pull request merged**
